diff Seven/Main.vm Seven/Main.vm.g
diff ConvertToBin/Main.vm ConvertToBin/Main.vm.g
diff Square/Square.vm Square/Square.vm.g
diff Square/SquareGame.vm Square/SquareGame.vm.g
diff Square/Main.vm Square/Main.vm.g
diff Average/Main.vm Average/Main.vm.g
diff Pong/Ball.vm Pong/Ball.vm.g
diff Pong/Bat.vm Pong/Bat.vm.g
diff Pong/Main.vm Pong/Main.vm.g
diff Pong/PongGame.vm Pong/PongGame.vm.g
diff ComplexArrays/Main.vm ComplexArrays/Main.vm.g
